# Generated by Django 6.1.1 on 2026-09-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Phụ tùng / Dịch vụ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá (VNĐ)')),
                ('is_part', models.BooleanField(default=True, verbose_name='Là phụ tùng')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số')),
                ('brand', models.CharField(max_length=50, verbose_name='Hãng xe')),
                ('model_name', models.CharField(max_length=50, verbose_name='Dòng xe')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Tình trạng xe')),
                ('status', models.CharField(choices=[('WAIT', 'Chờ xử lý'), ('DOING', 'Đang sửa'), ('DONE', 'Hoàn thành')], default='WAIT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('service_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicepart')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.workorder')),
            ],
        ),
    ]
