# Generated by Django 6.1.1 on 2026-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên linh kiện')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã linh kiện')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá nhập')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
